# Pandas

# file Read Write operation

In [1]:
import numpy as np
import pandas as pd
np.set_printoptions(precision=4)

In [3]:
import pandas as pd

draft1 = pd.read_csv('./ex1.csv')    # Supply the file name (path)

draft1.head(4)

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [4]:
draft2 = pd.read_table('./test.tsv')  # Read a tsv into a DataFrame

draft2.head()

        test   test test.1 test.2 test.3
sudh    sudh   sudh   sudh   sudh   sudh
kumar  kumar  kumar  kumar  kumar  kumar

In [5]:
df = pd.read_csv('./ex1.csv')
df

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [7]:
pd.read_table('./ex1.csv', sep=',')

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [8]:
pd.read_csv('./ex2.csv', header=None)

   0   1   2   3      4
0  1   2   3   4  hello
1  5   6   7   8  world
2  9  10  11  12    foo

In [11]:
df =pd.read_csv('./ex2.csv', names=['C1','C2', 'C3', 'C4', 'C5', 'C6'])
type(df)
df

   C1  C2  C3  C4     C5  C6
0   1   2   3   4  hello NaN
1   5   6   7   8  world NaN
2   9  10  11  12    foo NaN

In [12]:
!cat ./csv_mindex.csv

key1,key2,value1,value2
one,a,1,2
one,b,3,4
one,c,5,6
one,d,7,8
two,a,9,10
two,b,11,12
two,c,13,14
two,d,15,16

In [13]:

parsed = pd.read_csv('./csv_mindex.csv',
                     index_col=['key1', 'key2'])
parsed

           value1  value2
key1 key2
one  a          1       2
     b          3       4
     c          5       6
     d          7       8
two  a          9      10
     b         11      12
     c         13      14
     d         15      16

In [14]:
!cat ./ex4.csv
pd.read_csv('./ex4.csv', skiprows=[0, 2, 3])

# hey!
a,b,c,d,message
# just wanted to make things more difficult for you
# who reads CSV files with computers, anyway?
1,2,3,4,hello
5,6,7,8,world
9,10,11,12,foo

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [16]:
!cat ./ex5.csv

something,a,b,c,d,message
one,1,2,3,4,NA
two,5,6,,8,world
three,9,10,11,12,foo

In [17]:
result = pd.read_csv('./ex5.csv')
result
pd.isnull(result)

   something      a      b      c      d  message
0      False  False  False  False  False     True
1      False  False  False   True  False    False
2      False  False  False  False  False    False

In [18]:
result = pd.read_csv('./ex5.csv', na_values=['NULL'])
result

  something  a   b     c   d message
0       one  1   2   3.0   4     NaN
1       two  5   6   NaN   8   world
2     three  9  10  11.0  12     foo

In [21]:
url = "http://www.basketball-reference.com/leagues/NBA_2015_totals.html"

BB_data = pd.read_html(url)         # Read data from the specified url

In [22]:

BB_data

[      Rk          Player Pos Age   Tm   G  GS    MP   FG  FGA  ...   FT%  ORB  \
 0      1      Quincy Acy  PF  24  NYK  68  22  1287  152  331  ...  .784   79
 1      2    Jordan Adams  SG  20  MEM  30   0   248   35   86  ...  .609    9
 2      3    Steven Adams   C  21  OKC  70  67  1771  217  399  ...  .502  199
 3      4     Jeff Adrien  PF  28  MIN  17   0   215   19   44  ...  .579   23
 4      5   Arron Afflalo  SG  29  TOT  78  72  2502  375  884  ...  .843   27
 ..   ...             ...  ..  ..  ...  ..  ..   ...  ...  ...  ...   ...  ...
 670  490  Thaddeus Young  PF  26  TOT  76  68  2434  451  968  ...  .655  127
 671  490  Thaddeus Young  PF  26  MIN  48  48  1605  289  641  ...  .682   75
 672  490  Thaddeus Young  PF  26  BRK  28  20   829  162  327  ...  .606   52
 673  491     Cody Zeller   C  22  CHO  62  45  1487  172  373  ...  .774   97
 674  492    Tyler Zeller   C  25  BOS  82  59  1731  340  619  ...  .823  146

      DRB  TRB  AST  STL BLK  TOV   PF   PTS
 0    222  301   68   27  22   60  147   398
 1     19   28   16   16   7   14   24    94
 2    324  523   66   38  86   99  222   537
 3     54   77   15    4   9    9   30    60
 4    220  247  129   41   7  116  167  1035
 ..   ...  ...  ...  ...  ..  ...  ...   ...
 670  284  411  173  124  25  117  171  1071
 671  170  245  135   86  17   75  115   685
 672  114  166   38   38   8   42   56   386
 673  265  362  100   34  49   62  156   472
 674  319  465  113   18  52   76  205   833

 [675 rows x 30 columns]]

In [26]:
BB_data[0].iloc[:, 0:20].head(5)      # Check 5 rows (10 columns only)

,Rk,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,FG%,3P,3PA,3P%,2P,2PA,2P%,eFG%,FT,FTA
0,1,Quincy Acy,PF,24,NYK,68,22,1287,152,331,.459,18,60,.300,134,271,.494,.486,76,97
1,2,Jordan Adams,SG,20,MEM,30,0,248,35,86,.407,10,25,.400,25,61,.410,.465,14,23
2,3,Steven Adams,C,21,OKC,70,67,1771,217,399,.544,0,2,.000,217,397,.547,.544,103,205
3,4,Jeff Adrien,PF,28,MIN,17,0,215,19,44,.432,0,0,NaN,19,44,.432,.432,22,38
4,5,Arron Afflalo,SG,29,TOT,78,72,2502,375,884,.424,118,333,.354,257,551,.466,.491,167,198

In [27]:
titanic_train = pd.read_csv("https://gist.githubusercontent.com/michhar/2dfd2de0d4f8727f873422c5d959fff5/raw/ff414a1bcfcba32481e4d4e8db578e55872a2ca1/titanic.csv",
                           sep='\t')

In [28]:
titanic_train.head(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C

In [29]:
titanic_train[["Name","Pclass"]].head()

                                                Name  Pclass
0                            Braund, Mr. Owen Harris       3
1  Cumings, Mrs. John Bradley (Florence Briggs Th...       1
2                             Heikkinen, Miss. Laina       3
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)       1
4                           Allen, Mr. William Henry       3

In [30]:
titanic_train.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

In [31]:
pd.options.display.max_rows = 10

In [32]:
result = pd.read_csv('./ex6.csv')
result

           one       two     three      four key
0     0.467976 -0.038649 -0.295344 -1.824726   L
1    -0.358893  1.404453  0.704965 -0.200638   B
2    -0.501840  0.659254 -0.421691 -0.057688   G
3     0.204886  1.074134  1.388361 -0.982404   R
4     0.354628 -0.133116  0.283763 -0.837063   Q
...        ...       ...       ...       ...  ..
9995  2.311896 -0.417070 -1.409599 -0.515821   L
9996 -0.479893 -0.650419  0.745152 -0.646038   E
9997  0.523331  0.787112  0.486066  1.093156   K
9998 -0.362559  0.598894 -1.843201  0.887292   G
9999 -0.096376 -1.012999 -0.657431 -0.573315   0

[10000 rows x 5 columns]

In [33]:
pd.read_csv('./ex6.csv', nrows=5)

        one       two     three      four key
0  0.467976 -0.038649 -0.295344 -1.824726   L
1 -0.358893  1.404453  0.704965 -0.200638   B
2 -0.501840  0.659254 -0.421691 -0.057688   G
3  0.204886  1.074134  1.388361 -0.982404   R
4  0.354628 -0.133116  0.283763 -0.837063   Q

In [34]:
chunk = pd.read_csv('./ex6.csv', chunksize==1000)
chunk

Writing Data to Text Format

In [35]:
data = pd.read_csv('./ex5.csv')
data

  something  a   b     c   d message
0       one  1   2   3.0   4     NaN
1       two  5   6   NaN   8   world
2     three  9  10  11.0  12     foo

In [39]:
data.to_csv('./out1.csv')
!cat ./out1.csv

,something,a,b,c,d,message
0,one,1,2,3.0,4,
1,two,5,6,,8,world
2,three,9,10,11.0,12,foo

In [40]:
import sys
data.to_csv('./out1.csv', sep='@')

In [41]:
data.to_csv(sys.stdout, na_rep='NULL')

,something,a,b,c,d,message
0,one,1,2,3.0,4,NULL
1,two,5,6,NULL,8,world
2,three,9,10,11.0,12,foo

In [42]:
data.to_csv('./out2.csv', index=False, header=False)

In [43]:
data.to_csv('./out3.csv', index=False, columns=['a', 'b', 'c'])

In [44]:
dates = pd.date_range('1/1/2000', periods=7)
ts = pd.Series(np.arange(7), index=dates)
ts.to_csv('./tseries.csv')
!cat ./tseries.csv

,0
2000-01-01,0
2000-01-02,1
2000-01-03,2
2000-01-04,3
2000-01-05,4
2000-01-06,5
2000-01-07,6

Working with Delimited Formats

In [47]:
import csv
f = open('./ex7.csv')

reader = csv.reader(f)
reader

In [48]:
for line in reader:
    print(line)

['a', 'b', 'c']
['1', '2', '3']
['1', '2', '3']

In [49]:
with open('./ex7.csv') as f:
    lines = list(csv.reader(f))

In [50]:
header, values = lines[0], lines[1:]

In [51]:
data_dict = {h: v for h, v in zip(header, zip(*values))}
data_dict

{'a': ('1', '1'), 'b': ('2', '2'), 'c': ('3', '3')}

JSON Data

In [52]:
obj = """
{"name": "Wes",
 "places_lived": ["United States", "Spain", "Germany"],
 "pet": null,
 "siblings": [{"name": "Scott", "age": 30, "pets": ["Zeus", "Zuko"]},
              {"name": "Katie", "age": 38,
               "pets": ["Sixes", "Stache", "Cisco"]}]
}
"""

In [56]:
obj

'\n{"name": "Wes",\n "places_lived": ["United States", "Spain", "Germany"],\n "pet": null,\n "siblings": [{"name": "Scott", "age": 30, "pets": ["Zeus", "Zuko"]},\n              {"name": "Katie", "age": 38,\n               "pets": ["Sixes", "Stache", "Cisco"]}]\n}\n'

In [58]:
import json
result = json.loads(obj)
result

{'name': 'Wes',
 'places_lived': ['United States', 'Spain', 'Germany'],
 'pet': None,
 'siblings': [{'name': 'Scott', 'age': 30, 'pets': ['Zeus', 'Zuko']},
  {'name': 'Katie', 'age': 38, 'pets': ['Sixes', 'Stache', 'Cisco']}]}

In [59]:
asjson = json.dumps(result)

In [60]:
siblings = pd.DataFrame(result['siblings'], columns=['name', 'age','pets'])
siblings

    name  age                    pets
0  Scott   30            [Zeus, Zuko]
1  Katie   38  [Sixes, Stache, Cisco]

In [62]:
!cat ./example.json

[{"a": 1, "b": 2, "c": 3},
 {"a": 4, "b": 5, "c": 6},
 {"a": 7, "b": 8, "c": 9}]

In [63]:
data = pd.read_json('./example.json')
data

   a  b  c
0  1  2  3
1  4  5  6
2  7  8  9

In [64]:
print(data.to_json())
print(data.to_json(orient='records'))

{"a":{"0":1,"1":4,"2":7},"b":{"0":2,"1":5,"2":8},"c":{"0":3,"1":6,"2":9}}
[{"a":1,"b":2,"c":3},{"a":4,"b":5,"c":6},{"a":7,"b":8,"c":9}]

XML and HTML: Web Scraping

In [65]:
tables = pd.read_html('./fdic_failed_bank_list.html')
len(tables)

1

In [66]:
failures = tables[0]
failures.head()

,Bank Name,City,ST,CERT,Acquiring Institution,Closing Date,Updated Date
0,Allied Bank,Mulberry,AR,91,Today's Bank,"September 23, 2016","November 17, 2016"
1,The Woodbury Banking Company,Woodbury,GA,11297,United Bank,"August 19, 2016","November 17, 2016"
2,First CornerStone Bank,King of Prussia,PA,35312,First-Citizens Bank & Trust Company,"May 6, 2016","September 6, 2016"
3,Trust Company Bank,Memphis,TN,9956,The Bank of Fayette County,"April 29, 2016","September 6, 2016"
4,North Milwaukee State Bank,Milwaukee,WI,20364,First-Citizens Bank & Trust Company,"March 11, 2016","June 16, 2016"

In [67]:
close_timestamps = pd.to_datetime(failures['Closing Date'])

In [69]:
close_timestamps.dt.year.value_counts()
#close_timestamps

2010    157
2009    140
2011     92
2012     51
2008     25
       ...
2004      4
2001      4
2007      3
2003      3
2000      2
Name: Closing Date, Length: 15, dtype: int64

# Binary Data Formats

In [70]:
frame = pd.read_csv('./ex1.csv')
frame
frame.to_pickle('./frame_pickle')

In [71]:
pd.read_pickle('./frame_pickle')

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [73]:
!rm ./frame_pickle

Using HDF5 Format

In [75]:
frame = pd.DataFrame({'a': np.random.randn(100)})
store = pd.HDFStore('mydata.h5')
store['obj1'] = frame
store['obj1_col'] = frame['a']
store

<class 'pandas.io.pytables.HDFStore'>
File path: mydata.h5

In [80]:
store['obj1']

           a
0  -0.180130
1   0.568563
2  -0.898486
3   1.666743
4  -2.108685
..       ...
95 -0.586507
96  1.003355
97  0.786525
98  0.476489
99  0.410420

[100 rows x 1 columns]

In [81]:
store.put('obj2', frame, format='table')
store.select('obj2', where=['index >= 10 and index <= 15'])
store.close()

In [82]:
frame.to_hdf('mydata.h5', 'obj3', format='table')
pd.read_hdf('mydata.h5', 'obj3', where=['index < 5'])

          a
0 -0.180130
1  0.568563
2 -0.898486
3  1.666743
4 -2.108685

# Web APIs

In [83]:
import requests
url = 'https://api.github.com/repos/pandas-dev/pandas/issues'
resp = requests.get(url)
resp

In [85]:
data = resp.json()
data[2]['user']

{'login': 'jolespin',
 'id': 9061708,
 'node_id': 'MDQ6VXNlcjkwNjE3MDg=',
 'avatar_url': 'https://avatars1.githubusercontent.com/u/9061708?v=4',
 'gravatar_id': '',
 'url': 'https://api.github.com/users/jolespin',
 'html_url': 'https://github.com/jolespin',
 'followers_url': 'https://api.github.com/users/jolespin/followers',
 'following_url': 'https://api.github.com/users/jolespin/following{/other_user}',
 'gists_url': 'https://api.github.com/users/jolespin/gists{/gist_id}',
 'starred_url': 'https://api.github.com/users/jolespin/starred{/owner}{/repo}',
 'subscriptions_url': 'https://api.github.com/users/jolespin/subscriptions',
 'organizations_url': 'https://api.github.com/users/jolespin/orgs',
 'repos_url': 'https://api.github.com/users/jolespin/repos',
 'events_url': 'https://api.github.com/users/jolespin/events{/privacy}',
 'received_events_url': 'https://api.github.com/users/jolespin/received_events',
 'type': 'User',
 'site_admin': False}

In [86]:
data

[{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/33757',
  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',
  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/33757/labels{/name}',
  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/33757/comments',
  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/33757/events',
  'html_url': 'https://github.com/pandas-dev/pandas/pull/33757',
  'id': 605994731,
  'node_id': 'MDExOlB1bGxSZXF1ZXN0NDA4Mjk2MTY3',
  'number': 33757,
  'title': 'BUG: MonthOffset.name',
  'user': {'login': 'jbrockmendel',
   'id': 8078968,
   'node_id': 'MDQ6VXNlcjgwNzg5Njg=',
   'avatar_url': 'https://avatars1.githubusercontent.com/u/8078968?v=4',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/jbrockmendel',
   'html_url': 'https://github.com/jbrockmendel',
   'followers_url': 'https://api.github.com/users/jbrockmendel/followers',
   'following_url': 'https://api.github.com/users/jbrockmendel/following{/other_user}',
   'gists_url': 'https://api.github.com/users/jbrockmendel/gists{/gist_id}',
   'starred_url': 'https://api.github.com/users/jbrockmendel/starred{/owner}{/repo}',
   'subscriptions_url': 'https://api.github.com/users/jbrockmendel/subscriptions',
   'organizations_url': 'https://api.github.com/users/jbrockmendel/orgs',
   'repos_url': 'https://api.github.com/users/jbrockmendel/repos',
   'events_url': 'https://api.github.com/users/jbrockmendel/events{/privacy}',
   'received_events_url': 'https://api.github.com/users/jbrockmendel/received_events',
   'type': 'User',
   'site_admin': False},
  'labels': [],
  'state': 'open',
  'locked': False,
  'assignee': None,
  'assignees': [],
  'milestone': None,
  'comments': 0,
  'created_at': '2020-04-24T02:38:17Z',
  'updated_at': '2020-04-24T02:38:50Z',
  'closed_at': None,
  'author_association': 'MEMBER',
  'pull_request': {'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/33757',
   'html_url': 'https://github.com/pandas-dev/pandas/pull/33757',
   'diff_url': 'https://github.com/pandas-dev/pandas/pull/33757.diff',
   'patch_url': 'https://github.com/pandas-dev/pandas/pull/33757.patch'},
  'body': '- [ ] closes #xxxx\r\n- [x] tests added / passed\r\n- [x] passes `black pandas`\r\n- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`\r\n- [ ] whatsnew entry\r\n\r\n`is_anchored` is being accessed indirectly (its not a property).  As a result we never go down the other path, which would raise AttributeError since there is no `code_rule`.'},
 {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/33756',
  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',
  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/33756/labels{/name}',
  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/33756/comments',
  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/33756/events',
  'html_url': 'https://github.com/pandas-dev/pandas/issues/33756',
  'id': 605963140,
  'node_id': 'MDU6SXNzdWU2MDU5NjMxNDA=',
  'number': 33756,
  'title': 'BUG: DataFrame.truncate() returns incorrect data if the index is sorted in descending order',
  'user': {'login': 'francislan',
   'id': 7295453,
   'node_id': 'MDQ6VXNlcjcyOTU0NTM=',
   'avatar_url': 'https://avatars2.githubusercontent.com/u/7295453?v=4',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/francislan',
   'html_url': 'https://github.com/francislan',
   'followers_url': 'https://api.github.com/users/francislan/followers',
   'following_url': 'https://api.github.com/users/francislan/following{/other_user}',
   'gists_url': 'https://api.github.com/users/francislan/gists{/gist_id}',
   'starred_url': 'https://api.github.com/users/francislan/starred{/owner}{/repo}',
   'subscriptions_url': 'https://api.github.com/users/francislan/subscriptions',
   'organizations_url': 'https://api.github.com/users/francislan/orgs',
   'repos_url': 'https://api.github.com/users/francislan/repos',
   'events_url': 'https://api.github.com/users/francislan/events{/privacy}',
   'received_events_url': 'https://api.github.com/users/francislan/received_events',
   'type': 'User',
   'site_admin': False},
  'labels': [{'id': 76811,
    'node_id': 'MDU6TGFiZWw3NjgxMQ==',
    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Bug',
    'name': 'Bug',
    'color': 'e10c02',
    'default': False,
    'description': None},
   {'id': 1954720290,
    'node_id': 'MDU6TGFiZWwxOTU0NzIwMjkw',
    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Needs%20Triage',
    'name': 'Needs Triage',
    'color': '0052cc',
    'default': False,
    'description': 'Issue that has not been reviewed by a pandas team member'}],
  'state': 'open',
  'locked': False,
  'assignee': None,
  'assignees': [],
  'milestone': None,
  'comments': 0,
  'created_at': '2020-04-24T00:52:47Z',
  'updated_at': '2020-04-24T00:52:47Z',
  'closed_at': None,
  'author_association': 'NONE',
  'body': "- [x] I have checked that this issue has not already been reported.\r\n\r\n- [x] I have confirmed this bug exists on the latest version of pandas (1.0.3)\r\n\r\n- [ ] (optional) I have confirmed this bug exists on the master branch of pandas.\r\n\r\n---\r\n\r\n#### Code Sample, a copy-pastable example\r\n\r\n```python\r\ndf = pd.DataFrame(index=range(0, 5), data={'A': 1})\r\ndf.sort_index(ascending=False, inplace=True)\r\ndf.truncate(before=3)\r\n```\r\n\r\n#### Problem description\r\n\r\nWhen the index is sorted in descending order, the truncate() function behaves incorrectly. In the example above, it should truncate all rows whose index is < 3. Instead it is truncating all rows whose index is > 3.\r\nSimilarly when using after.\r\n\r\n#### Output\r\n\r\n```python\r\n>>> df\r\n   A\r\n4  1\r\n3  1\r\n2  1\r\n1  1\r\n0  1\r\n>>> df.truncate(before=3)\r\n   A\r\n3  1\r\n2  1\r\n1  1\r\n0  1\r\n```\r\n\r\n#### Expected Output\r\n\r\n```python\r\n>>> df.truncate(before=3)\r\n   A\r\n4  1\r\n3  1\r\n```\r\n\r\n#### Output of ``pd.show_versions()``\r\n\r\n<details>\r\n\r\nINSTALLED VERSIONS\r\n------------------\r\ncommit           : None\r\npython           : 3.7.7.final.0\r\npython-bits      : 64\r\nOS               : Darwin\r\nOS-release       : 19.4.0\r\nmachine          : x86_64\r\nprocessor        : i386\r\nbyteorder        : little\r\nLC_ALL           : None\r\nLANG             : en_US.UTF-8\r\nLOCALE           : en_US.UTF-8\r\n\r\npandas           : 1.0.3\r\nnumpy            : 1.18.2\r\npytz             : 2019.3\r\ndateutil         : 2.8.1\r\npip              : 20.0.2\r\nsetuptools       : 41.2.0\r\nCython           : None\r\npytest           : None\r\nhypothesis       : None\r\nsphinx           : None\r\nblosc            : None\r\nfeather          : None\r\nxlsxwriter       : None\r\nlxml.etree       : None\r\nhtml5lib         : None\r\npymysql          : None\r\npsycopg2         : None\r\njinja2           : None\r\nIPython          : None\r\npandas_datareader: None\r\nbs4              : None\r\nbottleneck       : None\r\nfastparquet      : None\r\ngcsfs            : None\r\nlxml.etree       : None\r\nmatplotlib       : 3.2.1\r\nnumexpr          : None\r\nodfpy            : None\r\nopenpyxl         : None\r\npandas_gbq       : None\r\npyarrow          : None\r\npytables         : None\r\npytest           : None\r\npyxlsb           : None\r\ns3fs             : None\r\nscipy            : None\r\nsqlalchemy       : None\r\ntables           : None\r\ntabulate         : None\r\nxarray           : None\r\nxlrd             : None\r\nxlwt             : None\r\nxlsxwriter       : None\r\nnumba            : None\r\n\r\n</details>\r\n"},
 {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/33754',
  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',
  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/33754/labels{/name}',
  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/33754/comments',
  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/33754/events',
  'html_url': 'https://github.com/pandas-dev/pandas/issues/33754',
  'id': 605909539,
  'node_id': 'MDU6SXNzdWU2MDU5MDk1Mzk=',
  'number': 33754,
  'title': 'ENH: .to_rpy2 method for DataFrame and Series',
  'user': {'login': 'jolespin',
   'id': 9061708,
   'node_id': 'MDQ6VXNlcjkwNjE3MDg=',
   'avatar_url': 'https://avatars1.githubusercontent.com/u/9061708?v=4',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/jolespin',
   'html_url': 'https://github.com/jolespin',
   'followers_url': 'https://api.github.com/users/jolespin/followers',
   'following_url': 'https://api.github.com/users/jolespin/following{/other_user}',
   'gists_url': 'https://api.github.com/users/jolespin/gists{/gist_id}',
   'starred_url': 'https://api.github.com/users/jolespin/starred{/owner}{/repo}',
   'subscriptions_url': 'https://api.github.com/users/jolespin/subscriptions',
   'organizations_url': 'https://api.github.com/users/jolespin/orgs',
   'repos_url': 'https://api.github.com/users/jolespin/repos',
   'events_url': 'https://api.github.com/users/jolespin/events{/privacy}',
   'received_events_url': 'https://api.github.com/users/jolespin/received_events',
   'type': 'User',
   'site_admin': False},
  'labels': [{'id': 76812,
    'node_id': 'MDU6TGFiZWw3NjgxMg==',
    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Enhancement',
    'name': 'Enhancement',
    'color': '4E9A06',
    'default': False,
    'description': None},
   {'id': 1954720290,
    'node_id': 'MDU6TGFiZWwxOTU0NzIwMjkw',
    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Needs%20Triage',
    'name': 'Needs Triage',
    'color': '0052cc',
    'default': False,
    'description': 'Issue that has not been reviewed by a pandas team member'}],
  'state': 'open',
  'locked': False,
  'assignee': None,
  'assignees': [],
  'milestone': None,
  'comments': 0,
  'created_at': '2020-04-23T22:16:29Z',
  'updated_at': '2020-04-23T22:30:12Z',
  'closed_at': None,
  'author_association': 'NONE',
  'body': "#### Is your feature request related to a problem?\r\n\r\nhttps://rpy2.github.io/doc/v3.0.x/html/generated_rst/pandas.html\r\nI've been using rpy2 a lot and considering that pandas was inspired from R it would be nice to have a .to_rpy2 method for seemless conversion. \r\n\r\n#### Describe the solution you'd like\r\n```\r\ndf = pd.DataFrame(data)\r\nr_df = df.to_rpy2()\r\n```\r\n#### API breaking implications\r\n\r\nIt shouldn't affect the API at all.  If `rpy2` isn't installed then throw an error just like writing excel files needs another package. \r\n\r\n#### Describe alternatives you've considered\r\n\r\nI made wrappers that I need to use. \r\n\r\n#### Additional context\r\n\r\nCurrent method with `rpy2` requires some boilerplate and is less seamless:\r\n\r\n\r\n![image](https://user-images.githubusercontent.com/9061708/80154923-64617d80-8575-11ea-98bf-1fb88d5a689b.png)\r\n\r\n\r\nHere's my current hack: \r\n\r\n![image](https://user-images.githubusercontent.com/9061708/80155790-4f85e980-8577-11ea-9498-8a8edbd2bebe.png)\r\n"},
 {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/33752',
  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',
  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/33752/labels{/name}',
  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/33752/comments',
  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/33752/events',
  'html_url': 'https://github.com/pandas-dev/pandas/issues/33752',
  'id': 605832644,
  'node_id': 'MDU6SXNzdWU2MDU4MzI2NDQ=',
  'number': 33752,
  'title': 'BUG: weekday property raises TypeError in groupby method',
  'user': {'login': 'philipphanemann',
   'id': 8366972,
   'node_id': 'MDQ6VXNlcjgzNjY5NzI=',
   'avatar_url': 'https://avatars3.githubusercontent.com/u/8366972?v=4',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/philipphanemann',
   'html_url': 'https://github.com/philipphanemann',
   'followers_url': 'https://api.github.com/users/philipphanemann/followers',
   'following_url': 'https://api.github.com/users/philipphanemann/following{/other_user}',
   'gists_url': 'https://api.github.com/users/philipphanemann/gists{/gist_id}',
   'starred_url': 'https://api.github.com/users/philipphanemann/starred{/owner}{/repo}',
   'subscriptions_url': 'https://api.github.com/users/philipphanemann/subscriptions',
   'organizations_url': 'https://api.github.com/users/philipphanemann/orgs',
   'repos_url': 'https://api.github.com/users/philipphanemann/repos',
   'events_url': 'https://api.github.com/users/philipphanemann/events{/privacy}',
   'received_events_url': 'https://api.github.com/users/philipphanemann/received_events',
   'type': 'User',
   'site_admin': False},
  'labels': [{'id': 76811,
    'node_id': 'MDU6TGFiZWw3NjgxMQ==',
    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Bug',
    'name': 'Bug',
    'color': 'e10c02',
    'default': False,
    'description': None},
   {'id': 1954720290,
    'node_id': 'MDU6TGFiZWwxOTU0NzIwMjkw',
    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Needs%20Triage',
    'name': 'Needs Triage',
    'color': '0052cc',
    'default': False,
    'description': 'Issue that has not been reviewed by a pandas team member'}],
  'state': 'open',
  'locked': False,
  'assignee': None,
  'assignees': [],
  'milestone': None,
  'comments': 0,
  'created_at': '2020-04-23T20:09:11Z',
  'updated_at': '2020-04-23T20:09:11Z',
  'closed_at': None,
  'author_association': 'CONTRIBUTOR',
  'body': "- [x] I have checked that this issue has not already been reported.\r\n\r\n- [x] I have confirmed this bug exists on the latest version of pandas.\r\n\r\n- [ ] (optional) I have confirmed this bug exists on the master branch of pandas.\r\n\r\n---\r\n\r\n#### Code Sample, a copy-pastable example\r\n\r\n```python\r\nimport pandas as pd\r\nn = 1000\r\ns = pd.Series(range(n), index=pd.date_range('2020-01-01', periods=n, freq='H'))\r\ns.groupby(lambda x: (x.weekday, x.hour)).mean()\r\n```\r\n\r\n#### Problem description\r\nUsed in the groupby method as a function argument in combination with  another index time attribute `weekday` raises a TypeError whereas `dayofweek` works although they are both aliases for each other. \r\n\r\n#### Expected Output\r\nI do expect the same output as with `\r\ns.groupby(lambda x: (x.dayofweek, x.hour)).mean()`\r\n\r\nsince it works as a single argument:\r\n\r\n `s.groupby(lambda x: x.dayofweek).mean().equals(s.groupby(lambda x: x.weekday).mean())`\r\n\r\n\r\n#### Output of ``pd.show_versions()``\r\n\r\nINSTALLED VERSIONS\r\n------------------\r\ncommit           : None\r\npython           : 3.8.2.final.0\r\npython-bits      : 64\r\nOS               : Linux\r\nOS-release       : 4.15.0-96-generic\r\nmachine          : x86_64\r\nprocessor        : x86_64\r\nbyteorder        : little\r\nLC_ALL           : None\r\nLANG             : de_DE.UTF-8\r\nLOCALE           : de_DE.UTF-8\r\n\r\npandas           : 1.0.3\r\nnumpy            : 1.18.1\r\npytz             : 2019.3\r\ndateutil         : 2.8.1\r\npip              : 20.0.2\r\nsetuptools       : 46.1.3.post20200330\r\nCython           : None\r\npytest           : None\r\nhypothesis       : None\r\nsphinx           : None\r\nblosc            : None\r\nfeather          : None\r\nxlsxwriter       : None\r\nlxml.etree       : None\r\nhtml5lib         : None\r\npymysql          : None\r\npsycopg2         : None\r\njinja2           : None\r\nIPython          : 7.13.0\r\npandas_datareader: None\r\nbs4              : None\r\nbottleneck       : None\r\nfastparquet      : None\r\ngcsfs            : None\r\nlxml.etree       : None\r\nmatplotlib       : None\r\nnumexpr          : None\r\nodfpy            : None\r\nopenpyxl         : None\r\npandas_gbq       : None\r\npyarrow          : None\r\npytables         : None\r\npytest           : None\r\npyxlsb           : None\r\ns3fs             : None\r\nscipy            : None\r\nsqlalchemy       : None\r\ntables           : None\r\ntabulate         : None\r\nxarray           : None\r\nxlrd             : None\r\nxlwt             : None\r\nxlsxwriter       : None\r\nnumba            : None\r\n</details>\r\n"},
 {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/33751',
  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',
  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/33751/labels{/name}',
  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/33751/comments',
  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/33751/events',
  'html_url': 'https://github.com/pandas-dev/pandas/pull/33751',
  'id': 605818819,
  'node_id': 'MDExOlB1bGxSZXF1ZXN0NDA4MTUyMzEx',
  'number': 33751,
  'title': 'TST: pd.NA TypeError in drop_duplicates with object dtype',
  'user': {'login': 'simonjayhawkins',
   'id': 13159005,
   'node_id': 'MDQ6VXNlcjEzMTU5MDA1',
   'avatar_url': 'https://avatars0.githubusercontent.com/u/13159005?v=4',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/simonjayhawkins',
   'html_url': 'https://github.com/simonjayhawkins',
   'followers_url': 'https://api.github.com/users/simonjayhawkins/followers',
   'following_url': 'https://api.github.com/users/simonjayhawkins/following{/other_user}',
   'gists_url': 'https://api.github.com/users/simonjayhawkins/gists{/gist_id}',
   'starred_url': 'https://api.github.com/users/simonjayhawkins/starred{/owner}{/repo}',
   'subscriptions_url': 'https://api.github.com/users/simonjayhawkins/subscriptions',
   'organizations_url': 'https://api.github.com/users/simonjayhawkins/orgs',
   'repos_url': 'https://api.github.com/users/simonjayhawkins/repos',
   'events_url': 'https://api.github.com/users/simonjayhawkins/events{/privacy}',
   'received_events_url': 'https://api.github.com/users/simonjayhawkins/received_events',
   'type': 'User',
   'site_admin': False},
  'labels': [{'id': 127685,
    'node_id': 'MDU6TGFiZWwxMjc2ODU=',
    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Testing',
    'name': 'Testing',
    'color': 'C4A000',
    'default': False,
    'description': None}],
  'state': 'open',
  'locked': False,
  'assignee': None,
  'assignees': [],
  'milestone': None,
  'comments': 0,
  'created_at': '2020-04-23T19:49:07Z',
  'updated_at': '2020-04-23T19:49:07Z',
  'closed_at': None,
  'author_association': 'MEMBER',
  'pull_request': {'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/33751',
   'html_url': 'https://github.com/pandas-dev/pandas/pull/33751',
   'diff_url': 'https://github.com/pandas-dev/pandas/pull/33751.diff',
   'patch_url': 'https://github.com/pandas-dev/pandas/pull/33751.patch'},
  'body': '- [ ] closes #32992\r\n- [ ] tests added / passed\r\n- [ ] passes `black pandas`\r\n- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`\r\n- [ ] whatsnew entry\r\n'},
 {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/33749',
  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',
  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/33749/labels{/name}',
  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/33749/comments',
  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/33749/events',
  'html_url': 'https://github.com/pandas-dev/pandas/pull/33749',
  'id': 605707197,
  'node_id': 'MDExOlB1bGxSZXF1ZXN0NDA4MDU5NDk4',
  'number': 33749,
  'title': 'BUG: Fix mixed datetime dtype inference',
  'user': {'login': 'dsaxton',
   'id': 2658661,
   'node_id': 'MDQ6VXNlcjI2NTg2NjE=',
   'avatar_url': 'https://avatars0.githubusercontent.com/u/2658661?v=4',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/dsaxton',
   'html_url': 'https://github.com/dsaxton',

In [151]:
issues = pd.DataFrame(data, columns=['number', 'title',
                                     'labels', 'state'])
issues

,number,title,labels,state
0,29270,"Reduce Benchmark Times of stat_ops, particular...","[{'id': 732775912, 'node_id': 'MDU6TGFiZWw3MzI...",open
1,29269,Add simple test for GH 28448,"[{'id': 78527356, 'node_id': 'MDU6TGFiZWw3ODUy...",open
2,29268,Named aggregations with multiple columns,[],open
3,29267,"API: public way to get the ""best values"" of a ...","[{'id': 35818298, 'node_id': 'MDU6TGFiZWwzNTgx...",open
4,29266,BLD: ABCSeries mapper maps unmapped categories...,"[{'id': 78527356, 'node_id': 'MDU6TGFiZWw3ODUy...",open
...,...,...,...,...
25,29229,API/DOC: an ExtensionDtype.__from_arrow__ meth...,"[{'id': 76865106, 'node_id': 'MDU6TGFiZWw3Njg2...",open
26,29227,Replace _has_complex_internals with isinstance...,"[{'id': 211029535, 'node_id': 'MDU6TGFiZWwyMTE...",open
27,29224,Period index 29204,"[{'id': 134699, 'node_id': 'MDU6TGFiZWwxMzQ2OT...",open
28,29223,CI: include pyarrow 0.15.0 / latest release in...,"[{'id': 48070600, 'node_id': 'MDU6TGFiZWw0ODA3...",open
29,29218,ENH: Show column name in assert_frame_equal,"[{'id': 76865106, 'node_id': 'MDU6TGFiZWw3Njg2...",open

# Interacting with Databases

In [87]:
import sqlite3
#connecting with the database.
db = sqlite3.connect("my_database4.db")
# Drop table if it already exist using execute() method.
db.execute("drop table if exists test")
query = """
CREATE TABLE test
(a VARCHAR(20), b VARCHAR(20),
 c REAL,        d INTEGER
);"""
con = sqlite3.connect('mydata2.sqlite')
con.execute(query)
con.commit()

In [88]:
data = [('Atlanta', 'Georgia', 1.25, 6),
        ('Tallahassee', 'Florida', 2.6, 3),
        ('Sacramento', 'California', 1.7, 5)]
stmt = "INSERT INTO test VALUES(?, ?, ?, ?)"
con.executemany(stmt, data)
con.commit()

In [89]:
cursor = con.execute('select * from test')
rows = cursor.fetchall()
rows

[('Atlanta', 'Georgia', 1.25, 6),
 ('Tallahassee', 'Florida', 2.6, 3),
 ('Sacramento', 'California', 1.7, 5)]

In [91]:
cursor.description

(('a', None, None, None, None, None, None),
 ('b', None, None, None, None, None, None),
 ('c', None, None, None, None, None, None),
 ('d', None, None, None, None, None, None))

In [92]:
pd.DataFrame(rows, columns=[x[0] for x in cursor.description])

             a           b     c  d
0      Atlanta     Georgia  1.25  6
1  Tallahassee     Florida  2.60  3
2   Sacramento  California  1.70  5

In [158]:
#!/usr/bin/python

import sqlite3
#connecting with the database.
db = sqlite3.connect("my_database5.db")
# Drop table if it already exist using execute() method.
db.execute("drop table if exists grades1")
# Create table as per requirement
db.execute("create table grades1(id int, name text, score int)")
#inserting values inside the created table
db.execute("insert into grades1(id, name, score) values(101, 'John',99 )")
db.execute("insert into grades1(id, name, score) values(102, 'Gary',90 )")
db.execute("insert into grades1(id, name, score) values(103, 'James', 80 )")
db.execute("insert into grades1(id, name, score) values(104, 'Cathy', 85 )")
db.execute("insert into grades1(id, name, score) values(105, 'Kris',95 )")

In [159]:
db.commit()

In [160]:
results = db.execute("select * from grades1 order by id")
for row in results:
    print((row))
print("-" * 60 )

(101, 'John', 99)
(102, 'Gary', 90)
(103, 'James', 80)
(104, 'Cathy', 85)
(105, 'Kris', 95)
------------------------------------------------------------

In [161]:
results = db.execute("select * from grades1 where name = 'Gary' ")
for row in results: print(row)
print("-"* 60 )

(102, 'Gary', 90)
------------------------------------------------------------

In [162]:
results = db.execute("select * from grades1 where score >= 90 ")
for row in results:
    print(row)
print("-" * 60 )

(101, 'John', 99)
(102, 'Gary', 90)
(105, 'Kris', 95)
------------------------------------------------------------

In [163]:
results = db.execute("select name, score from grades1 order by score desc ")
for row in results:
    print(row)
print("-" * 60 )

('John', 99)
('Kris', 95)
('Gary', 90)
('Cathy', 85)
('James', 80)
------------------------------------------------------------

In [164]:
results = db.execute("select name, score from grades1 order by score")
for row in results:
    print(row)
print("-" * 60 )

('James', 80)
('Cathy', 85)
('Gary', 90)
('Kris', 95)
('John', 99)
------------------------------------------------------------

In [67]:
results = db.execute("select name, score from grades1 order by score")
for row in results:
    print(row)

('James', 80)
('Cathy', 85)
('Gary', 90)
('Kris', 95)
('John', 99)